### ISSUE TITLE
filter 1:1 events between two participants

### ISSUE THREAD

**Issue by isha689** [nylas/nylas-python#261] opened 2023-05-06 11:41 UTC
**Is your feature request related to a problem? Please describe.**

I have a usecase where I want to fetch only the 1:1 events between two people. What is the workaround for this?

I have been trying to make a request like this: https://api.nylas.com/events?limit=10&participants=["email1","email2"]
This doesn't seem to work. Please help!

**Comment by atejada** [comment] 2023-05-09 22:59
Hi @isha689 Well, if you do something like this:

```
participant_1 = "me@nylas.com"
participant_2 = "you@nylas.com"

today = date.today()
AFTER = int(datetime.datetime(today.year, today.month, today.day, 0, 0, 0).strftime('%s'))

events = nylas.events.where(limit=20, participants=[participant_1,participant_2], starts_after=AFTER)
for event in events:
    print(event.title)
```

This is going to return all the events where any of the participants are included, the problem is that is going to show you events that might have extra participants...or just one participant...the filter doesn't exclude extra participants, which is not necessary something bad...

Anyways...you could something like this:

```
participant_1 = "alvaro.t@nylas.com"
participant_2 = "ash.a@nylas.com"
counter = 0

today = date.today()
AFTER = int(datetime.datetime(today.year, today.month, today.day, 0, 0, 0).strftime('%s'))

events = nylas.events.where(limit=20, participants=[participant_1,participant_2], starts_after=AFTER)
for event in events:
    if len(event.participants) == 2:
        for participant in event.participants:
            if participant["email"] == participant_1 or participant["email"] == participant_2:
                counter += 1
        if counter == 2:
            counter = 0
            print(event.title)
``` 

You are filtering event that have only two participants, and you're making sure that both participants are the ones you want to filter on...

Hope that helps you out 😀

**Comment by isha689** [comment] 2023-05-11 06:09
Thanks @atejada for your reply. 
Yes, I also thought of comparing the length and participant email after fetching the events but with this I end up with the problem of pagination.
Suppose I fetched 20 events and none of them are having only 2 participants, this way it will return me 0 events and I will end up telling my user that they don't have any 1:1 events with the given participant, while they might have such events in the next 20 or 50 events

**Comment by isha689** [comment] 2023-05-12 07:36
Thank you @atejada for this.

Also, do you have any date in mind by when this feature will be released ?

**Comment by mrashed-dev** [comment] 2024-03-06 23:47
Sorry for the delay on this response but this has been resolved in the new Nylas API v3 and subsequently the Nylas Python SDK v6. You can now filter events using the `attendees` field by providing a comma-delimited list of emails.

**Closed by mrashed-dev** 2024-03-06 23:47 UTC
Labels: enhancement
