### ISSUE TITLE
v3 / v6.0.0 `CreateParticipant` has unlisted field `status`

### ISSUE THREAD

**Issue by samatgrow** [nylas/nylas-python#316] opened 2023-11-30 20:44 UTC
**Describe the bug**
The v3 Python SDK's [CreateParticipant has a status field](https://github.com/nylas/nylas-python/blob/v6.0.0-beta/nylas/models/events.py#L350) that is not listed in [the underlying API's documentation](https://developer.nylas.com/docs/api/v3-beta/ecc/#post-/v3/grants/-grant_id-/events). I assume this is a holdover from the Participant class (used for returning event data), which correctly does have a status field. Am I misunderstanding the intention of the field?

**Expected behavior**
Expected SDK fields to match API, I'm not sure I'd ever want to set participant status (or that I'm allowed to).

**SDK Version:**
6.0.0

EDIT: To clarify this isn't blocking us at all, ignoring the field seems to have no consequences.

**Comment by samatgrow** [comment] 2023-12-01 01:59
Similarly, `CreateEventRequest` has a `read_only` property that the API docs say is unsettable.

**Comment by mrashed-dev** [comment] 2023-12-01 19:59
@samatgrow Thank you so much for catching these inaccuracies! A PR will be open soon to make it better aligned with the API.

**Comment by samatgrow** [comment] 2023-12-06 02:39
Thanks for the quick fixes! Found a small typo, this time on `6.0.0b7`: `ListCalendersQueryParams` should be ListCalend**a**rsQueryParams.

**Comment by samatgrow** [comment] 2023-12-06 14:15
`ListEventQueryParams` accepts `str` for `start` and `end` while other methods that accept timestamps accept `int` which seemed a bit clearer from my perspective. I can open new issues for these if you like, just figured they didn't each deserve an entire issue but LMK what you prefer 😄

**Comment by mrashed-dev** [comment] 2023-12-11 22:42
@samatgrow Thanks for reporting these issues! Having them in this issue is fine until it's closed by a PR, if you notice any other mistakes after the issue is closed feel free to open another one :)

Regarding your latest feedback, thanks for catching the typo on Calendars and the suggestion for Event. I'll add these two to the PR 😄

**Comment by mrashed-dev** [comment] 2024-01-04 21:30
This fix is now released in v6 beta 8: https://pypi.org/project/nylas/6.0.0b8/

**Closed by mrashed-dev** 2024-01-04 21:30 UTC
Labels: bug
